### ISSUE TITLE
Kat: Line is not printed on flush

### ISSUE THREAD

**Issue by frap129** [TytanRock/CS-231-Projects#1]
Seems like your code is suffering the same issue as mine. Using Ctrl+D to simulate EOF on a non-blank line causes a line flush, then Ctrl+D again actually ends the file. Both your version and mine require Ctrl+D to be hit twice before a line from stdin is printed. GNU cat prints the line after the line flush (first Ctrl+D) and allows the user to continue input. I'm 99% certain Vineyard won't check something this obscure, but I thought I'd let you know.

**Comment by TytanRock** [comment]
Looking more at the source code from linux, [relevant lines](https://github.com/coreutils/coreutils/blob/6d78a28078feb6bfd26c6f1cc0ddbb0a356514c4/src/cat.c#L665-L668) (I think?), cat uses a different way to get user input. Since Vineyward  told us to use fgets in this assignment, I'd say this isn't an issue.
